# Generated by Django 5.1.2 on 2024-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="VIP статус"),
                ),
                (
                    "duration_value",
                    models.PositiveIntegerField(verbose_name="Длительность"),
                ),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("days", "Дни"),
                            ("weeks", "Недели"),
                            ("months", "Месяцы"),
                            ("years", "Года"),
                        ],
                        default="days",
                        verbose_name="Период",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "💵 Тариф",
                "verbose_name_plural": "💵 Тарифы",
            },
        ),
    ]
