# Generated by Django 5.1.2 on 2025-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="partner_bonuses",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество бонусов для партнёра при оплате"
            ),
        ),
    ]
