# Generated by Django 5.1.2 on 2025-02-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0002_tariff_partner_bonuses"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "✅ Оплачено"),
                            ("balance", "💰 Списано с баланса"),
                            ("wait", "🕒 Ожидает оплаты"),
                            ("cancel", "❌ Отклонён"),
                        ],
                        default="wait",
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(blank=True, null=True, verbose_name="ID платежа"),
                ),
                (
                    "payed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отмены операции"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tariff_receipts",
                        to="tariffs.tariff",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_receipts",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "📃 Операция",
                "verbose_name_plural": "📃 Операции",
            },
        ),
    ]
