# Generated by Django 5.1.2 on 2025-02-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tariffs", "0003_receipt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "verbose_name": "📃 Оплата конфига",
                "verbose_name_plural": "📃 Оплаты конфигов",
            },
        ),
    ]
