# Generated by Django 5.1.2 on 2024-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(unique=True, verbose_name="Telegram ID"),
                ),
                ("full_name", models.CharField(verbose_name="Имя")),
                (
                    "username",
                    models.CharField(blank=True, null=True, verbose_name="Юзернейм"),
                ),
                (
                    "earned",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Заработано"
                    ),
                ),
                (
                    "balance",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Баланс"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
            options={
                "verbose_name": "👤 Пользователь",
                "verbose_name_plural": "👤 Пользователи",
            },
        ),
    ]
