# Generated by Django 5.1.2 on 2024-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("done", "✅ Выполнена"),
                    ("wait", "🕒 Ожидает"),
                    ("cancel", "❌ Отклонена"),
                ],
                default="wait",
                max_length=10,
                verbose_name="Статус операции",
            ),
        ),
    ]
