# Generated by Django 5.1.2 on 2025-04-23 11:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(max_length=4096, verbose_name='Содержание рассылки')),
                ('scheduled_time', models.DateTimeField(verbose_name='Расписание отправки')),
                ('created_at', models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)),
                ('completed', models.BooleanField(verbose_name="Выполнено", default=False)),
            ],
            options={
                'verbose_name': '✉️ Рассылка',
                'verbose_name_plural': '✉️ Рассылки',
            },
        ),
    ]
