# Generated by Django 5.1.2 on 2024-12-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tariffs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "✅ Оплачено"),
                            ("wait", "🕒 Ожидает оплаты"),
                            ("cancel", "❌ Отклонён"),
                        ],
                        default="wait",
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "config_name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Название конфига"
                    ),
                ),
                (
                    "payed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "expiring_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания тарифа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания чека"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs",
                        to="tariffs.tariff",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "📝 Конфиг",
                "verbose_name_plural": "📝 Конфиги",
            },
        ),
    ]
