# Generated by Django 5.1.2 on 2024-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата отмены операции"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
