# Generated by Django 5.1.2 on 2025-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("done", "✅ Оплачено"),
                    ("wait", "🕒 Ожидает оплаты"),
                    ("cancel", "❌ Отклонён"),
                ],
                default="wait",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="status",
            field=models.CharField(
                choices=[("enable", "✅ Активен"), ("disable", "❌ Неактивен")],
                default="disable",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
