# Generated by Django 5.1.2 on 2025-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0002_config_payment_status_alter_config_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="active",
            field=models.CharField(
                choices=[
                    ("connected", "✅ Подключен"),
                    ("disconnected", "❌ Отключён"),
                ],
                default="disconnected",
                max_length=12,
                verbose_name="Статус подключения",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("done", "✅ Оплачено"),
                    ("balance", "💰 Списано с баланса"),
                    ("wait", "🕒 Ожидает оплаты"),
                    ("cancel", "❌ Отклонён"),
                ],
                default="wait",
                max_length=10,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="status",
            field=models.CharField(
                choices=[("enable", "✅ Активен"), ("disable", "❌ Неактивен")],
                default="disable",
                max_length=10,
                verbose_name="Статус активности",
            ),
        ),
    ]
