# Generated by Django 5.1.2 on 2025-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0003_config_active_alter_config_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="payment_id",
            field=models.CharField(blank=True, null=True, verbose_name="ID платежа"),
        ),
    ]
