# Generated by Django 5.1.2 on 2025-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0004_config_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="is_sub",
            field=models.BooleanField(default=True, verbose_name="Подписка активна"),
        ),
    ]
