# Generated by Django 5.1.2 on 2025-02-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configs", "0005_config_is_sub"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="config",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="config",
            name="payed_at",
        ),
        migrations.RemoveField(
            model_name="config",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="config",
            name="payment_status",
        ),
    ]
