# Generated by Django 5.1.2 on 2025-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_config_receipt_alter_config_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='payment_method_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID метод оплаты'),
        ),
    ]
