# Generated by Django 5.1.2 on 2024-12-21 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQTheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
            ],
            options={
                "verbose_name": "🗂 Тема",
                "verbose_name_plural": "🗂 Темы",
            },
        ),
        migrations.CreateModel(
            name="FAQProblem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(verbose_name="Проблема")),
                ("solution", models.TextField(verbose_name="Решение проблемы")),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faq.faqtheme",
                        verbose_name="Тема проблемы",
                    ),
                ),
            ],
            options={
                "verbose_name": "❓ Проблема",
                "verbose_name_plural": "❓ Проблемы",
            },
        ),
    ]
